FROM openfoam/openfoam11-paraview510
USER root

RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y \
    sudo \
    git \
    python3.10 \
    python3.10-distutils \
    && rm -rf /var/lib/apt/lists/*

# エイリアスを設定
RUN echo 'alias python="/usr/bin/python3.10"' >>  ~/.bashrc
# pipは下記で入れる
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10


# ライブラリ
RUN pip install \
    ipykernel \
    vtk \
    git+https://github.com/mathLab/smithers.git

WORKDIR /home/openfoam
# USER openfoam